[package]
name = "bad-apple-flut"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "1.3.3"
clap = { version = "4.4.15", features = ["derive"] }
crossterm = "0.27.0"
ffmpeg-next = "6.1.1"
rand = "0.8.5"
rayon = "1.8.0"
serde = { version = "1.0.195", features = ["derive"] }
toml = "0.8.8"
